# https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Cross_Compile_Mozilla_for_Mingw32
# https://docs.travis-ci.com/user/environment-variables/

language: cpp
os: linux
dist: xenial
arch: amd64
sudo: required
compiler: clang
cache:
  directories:
  - $HOME/tarballs

before_install:
- dpkg --add-architecture i386
- sudo apt-get update -qy
- sudo mkdir -p /builds/worker/fetches/mingw32/
install:
- sudo apt-get install -y zstd win32
- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
- export NVM_DIR="$HOME/.nvm"
- source "$NVM_DIR/nvm.sh"  # This loads nvm
- source "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
- nvm install v10.19
- sudo apt-get install -y yasm nasm autoconf2.13

script:
- if ! [ -f $HOME/tarballs/clangmingw.tar.zst ]; then curl -kL "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-9-mingw-x86.latest/artifacts/public/build/clangmingw.tar.zst" -o $HOME/tarballs/clangmingw.tar.zst; fi
- if ! [ -f $HOME/tarballs/rustc.tar.zst ]; then curl -kL "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.mingw32-rust-1.43.latest/artifacts/public/build/rustc.tar.zst" -o $HOME/tarballs/rustc.tar.zst; fi
- if ! [ -f $HOME/tarballs/cbindgen.tar.xz ]; then curl -kL "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-cbindgen.latest/artifacts/public/build/cbindgen.tar.xz" -o $HOME/tarballs/cbindgen.tar.xz; fi
- if ! [ -f $HOME/tarballs/nsis.tar.xz ]; then curl -kL "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-mingw32-nsis.latest/artifacts/public/build/nsis.tar.xz" -o $HOME/tarballs/nsis.tar.xz; fi
- if ! [ -f $HOME/tarballs/fxc2.tar.xz ]; then curl -kL "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-mingw-fxc2-x86.latest/artifacts/public/build/fxc2.tar.xz" -o $HOME/tarballs/fxc2.tar.xz; fi

- tar -I zstd -xf $HOME/tarballs/clangmingw.tar.zst
- tar -I zstd -xf $HOME/tarballs/rustc.tar.zst
- tar -xJpf $HOME/tarballs/cbindgen.tar.xz
- tar -xJpf $HOME/tarballs/nsis.tar.xz
- tar -xJpf $HOME/tarballs/fxc2.tar.xz

- sudo cp -rf ./mingw32/* /builds/worker/fetches/mingw32/
- export PATH=$PATH:$TRAVIS_BUILD_DIR/fxc2
- find $TRAVIS_BUILD_DIR -type d -maxdepth 3

- mkdir -p mozilla-central
- cd mozilla-central
- git init
- git remote add origin https://github.com/imharrywu/mozilla-central
- git fetch origin master
- git checkout -b master origin/master

- /home/travis/build/imharrywu/firefox-win-crossbuild/clang/bin/i686-w64-mingw32-clang --version

- cp -f $TRAVIS_BUILD_DIR/.mozconfig ./
- ./mach build


